import type { PlanData } from './types'

export const PLANS: PlanData[] = [
  {
    id: 'free',
    displayName: 'Free',
    priceMonthly: 0,
    priceAnnual: 0,
    description: 'Para explorar la plataforma',
    popular: false,
    features: [
      { name: 'Hasta 5 usuarios', included: true },
      { name: '1 GB almacenamiento', included: true },
      { name: '1,000 llamadas API/mes', included: true },
      { name: 'Roles personalizados', included: false },
      { name: 'MFA', included: false },
      { name: 'SSO/SAML', included: false },
      { name: 'Soporte prioritario', included: false },
    ],
  },
  {
    id: 'starter',
    displayName: 'Starter',
    priceMonthly: 29,
    priceAnnual: 313,
    description: 'Para pequeños equipos en crecimiento',
    popular: false,
    features: [
      { name: 'Hasta 10 usuarios', included: true },
      { name: '5 GB almacenamiento', included: true },
      { name: '10,000 llamadas API/mes', included: true },
      { name: 'Roles personalizados', included: true },
      { name: 'MFA', included: false },
      { name: 'SSO/SAML', included: false },
      { name: 'Soporte por email', included: true },
    ],
  },
  {
    id: 'professional',
    displayName: 'Professional',
    priceMonthly: 79,
    priceAnnual: 854,
    description: 'Para empresas que necesitan escala y control',
    popular: true,
    features: [
      { name: 'Hasta 25 usuarios', included: true },
      { name: '20 GB almacenamiento', included: true },
      { name: '100,000 llamadas API/mes', included: true },
      { name: 'Roles personalizados ilimitados', included: true },
      { name: 'MFA obligatorio', included: true },
      { name: 'SSO/SAML', included: false },
      { name: 'Soporte prioritario', included: true },
    ],
  },
  {
    id: 'enterprise',
    displayName: 'Enterprise',
    priceMonthly: 199,
    priceAnnual: 2149,
    description: 'Para grandes organizaciones',
    popular: false,
    features: [
      { name: 'Usuarios ilimitados', included: true },
      { name: 'Almacenamiento ilimitado', included: true },
      { name: 'Llamadas API ilimitadas', included: true },
      { name: 'Roles personalizados ilimitados', included: true },
      { name: 'MFA obligatorio', included: true },
      { name: 'SSO/SAML', included: true },
      { name: 'Soporte dedicado 24/7', included: true },
    ],
  },
]
